name: Action1

on: push

jobs: 
  action1job: 
    runs-on: ubuntu-latest
    steps:
      - name: One Command
        run: echo "Master"
      - name: Multi commands
        run: |
          npm -v
          echo "Checked NPM Version"
      - name: Python
        run: |
          import platform
          print(platform.processor())
        shell: python

  Windows-One: 
    runs-on: windows-latest
    steps: 
      - name: Powershell
        run: Get-Location



        