name: Running First Action

on: push

jobs:
  actionplaytime:
    runs-on: ubuntu-latest
    steps:
      - name: GreetMe
        id: outp
        uses: actions/hello-world-javascript-action@v1
        with: 
          who-to-greet: Vipin Rawat

      - name: OutputAction1s11aada
        run: |
          echo "Greeting was made on"
          echo "${{ steps.outp.outputs.time }}"